name: Store Front CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build store-front-final -f store-front-final/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/store-front:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/store-front:latest
